"""Embedded trade data - auto-generated from DT_OrderDecks.json

This module contains the pre-parsed merchant and order data from the game.
Do not edit manually - regenerate from the JSON source if needed.
"""

# Trade data format: list of (raw_name, display_name, orders)
# Orders format: list of (raw_name, display_name)
MERCHANTS_DATA: list[tuple[str, str, list[tuple[str, str]]]] = [
    (
        "ArnorOrders_Default",
        "Arnor",
        [
            ("CarvedMuralSections_Order_Default", "Carved Mural Sections"),
            ("GoldSilverFilligree_Order_Default", "Gold Silver Filligree"),
            ("RunicHearthstones_Order_Default", "Runic Hearthstones"),
            ("BuildingHouseingTools_Order_Default", "Building Houseing Tools"),
            ("OrnateMetalwork_Order_Default", "Ornate Metalwork"),
            ("Cabbage_Order_Default", "Cabbage"),
            ("Granite_Order_Default", "Granite"),
            ("IronWood_Order_Default", "Iron Wood"),
            ("MountainPotato_Order_Default", "Mountain Potato"),
            ("SilverCoin_Order_Default", "Silver Coin"),
        ],
    ),
    (
        "BlueMountainOrders_Default",
        "Blue Mountain",
        [
            ("CrystalLamp_Order_Default", "Crystal Lamp"),
            ("MirroredGlass_Order_Default", "Mirrored Glass"),
            ("CrossbowLot_Order_Default", "Crossbow Lot"),
            ("DwarvenArrowheads_Order_Default", "Dwarven Arrowheads"),
            ("OrnateMetalwork_Order_Default", "Ornate Metalwork"),
            ("Adamant_Order_Default", "Adamant"),
            ("Amber_Order_Default", "Amber"),
            ("CopperIngot_Order_Default", "Copper Ingot"),
            ("Diamond_Order_Default", "Diamond"),
            ("GoldCoin_Order_Default", "Gold Coin"),
            ("GoldIngot_Order_Default", "Gold Ingot"),
            ("RedBeryl_Order_Default", "Red Beryl"),
            ("Sapphire_Order_Default", "Sapphire"),
        ],
    ),
    (
        "GondorOrders_Default",
        "Gondor",
        [
            ("CrystalLamp_Order_Default", "Crystal Lamp"),
            ("MechanicalToy_Order_Default", "Mechanical Toy"),
            ("BronzeShipFitting_Order_Default", "Bronze Ship Fitting"),
            ("BuildingHouseingTools_Order_Default", "Building Houseing Tools"),
            ("CeremonialArmorLot_Order_Default", "Ceremonial Armor Lot"),
            ("CeremonialWeaponLot_Order_Default", "Ceremonial Weapon Lot"),
            ("DecorativeMithrilWork_Order_Default", "Decorative Mithril Work"),
            ("SteelWeaponLot_Order_Default", "Steel Weapon Lot"),
            ("Adamant_Order_Default", "Adamant"),
            ("Diamond_Order_Default", "Diamond"),
            ("Rubies_Order_Default", "Rubies"),
            ("Scales_Order_Default", "Scales"),
            ("SilverCoin_Order_Default", "Silver Coin"),
        ],
    ),
    (
        "GundabadOrders_Default",
        "Gundabad",
        [
            ("HealingSupplies_Order_Default", "Healing Supplies"),
            ("CrossbowLot_Order_Default", "Crossbow Lot"),
            ("EliteArmor_Order_Default", "Elite Armor"),
            ("EliteWeapons_Order_Default", "Elite Weapons"),
            ("SteelWeaponLot_Order_Default", "Steel Weapon Lot"),
            ("TrebuchetParts_Order_Default", "Trebuchet Parts"),
            ("SaltedMeat_Order_Default", "Salted Meat"),
            ("Cabbage_Order_Default", "Cabbage"),
            ("Flares_Order_Default", "Flares"),
            ("IronIngots_Order_Default", "Iron Ingots"),
            ("IronWood_Order_Default", "Iron Wood"),
            ("Leather_Order_Default", "Leather"),
            ("MountainPotato_Order_Default", "Mountain Potato"),
            ("Scales_Order_Default", "Scales"),
            ("SteelIngots_Order_Default", "Steel Ingots"),
        ],
    ),
    (
        "LothlorienOrders_Default",
        "Lothlorien",
        [
            ("DiamondJewelry_Order_Default", "Diamond Jewelry"),
            ("EngravedAkhfurChests_Order_Default", "Engraved Akhfur Chests"),
            ("GemSetFiligreeInlay_Order_Default", "Gem Set Filigree Inlay"),
            ("GoldJewelry_Order_Default", "Gold Jewelry"),
            ("MirroredGlass_Order_Default", "Mirrored Glass"),
            ("MithrilJewelry_Order_Default", "Mithril Jewelry"),
            ("OrnateTablewear_Order_Default", "Ornate Tablewear"),
            ("BronzeShipFitting_Order_Default", "Bronze Ship Fitting"),
            ("CeremonialArmorLot_Order_Default", "Ceremonial Armor Lot"),
            ("CeremonialWeaponLot_Order_Default", "Ceremonial Weapon Lot"),
            ("DwarvenArrowheads_Order_Default", "Dwarven Arrowheads"),
            ("WoodworkingTools_Order_Default", "Woodworking Tools"),
            ("Emeralds_Order_Default", "Emeralds"),
            ("NaturalFiber_Order_Default", "Natural Fiber"),
            ("StarmetalCoins_Order_Default", "Starmetal Coins"),
        ],
    ),
    (
        "RedMountainOrders_Default",
        "Red Mountain",
        [
            ("DiamondJewelry_Order_Default", "Diamond Jewelry"),
            ("GoldSilverFilligree_Order_Default", "Gold Silver Filligree"),
            ("DecorativeMithrilWork_Order_Default", "Decorative Mithril Work"),
            ("EliteArmor_Order_Default", "Elite Armor"),
            ("EliteWeapons_Order_Default", "Elite Weapons"),
            ("PrecisionMeasurementTools_Order_Default", "Precision Measurement Tools"),
            ("WoodworkingTools_Order_Default", "Woodworking Tools"),
            ("Adamant_Order_Default", "Adamant"),
            ("Amber_Order_Default", "Amber"),
            ("BlackDiamonds_Order_Default", "Black Diamonds"),
            ("DurinulIngots_Order_Default", "Durinul Ingots"),
            ("Emeralds_Order_Default", "Emeralds"),
            ("GoldCoin_Order_Default", "Gold Coin"),
            ("GoldIngot_Order_Default", "Gold Ingot"),
            ("Lembas_Order_Default", "Lembas"),
            ("SilverIngots_Order_Default", "Silver Ingots"),
        ],
    ),
    (
        "RivendellOrders_Default",
        "Rivendell",
        [
            ("CarvedMuralSections_Order_Default", "Carved Mural Sections"),
            ("CrystalLamp_Order_Default", "Crystal Lamp"),
            ("DwarvenHistories_Order_Default", "Dwarven Histories"),
            ("EngravedAkhfurChests_Order_Default", "Engraved Akhfur Chests"),
            ("GemSetFiligreeInlay_Order_Default", "Gem Set Filigree Inlay"),
            ("OrnateTablewear_Order_Default", "Ornate Tablewear"),
            ("CeremonialArmorLot_Order_Default", "Ceremonial Armor Lot"),
            ("CeremonialWeaponLot_Order_Default", "Ceremonial Weapon Lot"),
            ("OrnateMetalwork_Order_Default", "Ornate Metalwork"),
            ("Anorin_Order_Default", "Anorin"),
            ("Diamond_Order_Default", "Diamond"),
            ("Iolite_Order_Default", "Iolite"),
            ("Scales_Order_Default", "Scales"),
            ("StarmetalCoins_Order_Default", "Starmetal Coins"),
        ],
    ),
    (
        "RohanOrders_Default",
        "Rohan",
        [
            ("CrystalLamp_Order_Default", "Crystal Lamp"),
            ("RunicHearthstones_Order_Default", "Runic Hearthstones"),
            ("TravelingGear_Order_Default", "Traveling Gear"),
            ("HorsemansIronwork_Order_Default", "Horsemans Ironwork"),
            ("IronPotsAndPans_Order_Default", "Iron Pots And Pans"),
            ("OrnateMetalwork_Order_Default", "Ornate Metalwork"),
            ("SteelWeaponLot_Order_Default", "Steel Weapon Lot"),
            ("WoodworkingTools_Order_Default", "Woodworking Tools"),
            ("Amethyst_Order_Default", "Amethyst"),
            ("Garnet_Order_Default", "Garnet"),
            ("GoldIngot_Order_Default", "Gold Ingot"),
            ("IronWood_Order_Default", "Iron Wood"),
            ("Jade_Order_Default", "Jade"),
            ("BronzeCoins_Order_Default", "Bronze Coins"),
        ],
    ),
    (
        "ShireOrders_Default",
        "Shire",
        [
            ("BrassButtons_Order_Default", "Brass Buttons"),
            ("CopperBeltBuckles_Order_Default", "Copper Belt Buckles"),
            ("MechanicalToy_Order_Default", "Mechanical Toy"),
            ("RunicHearthstones_Order_Default", "Runic Hearthstones"),
            ("TravelingGear_Order_Default", "Traveling Gear"),
            ("BuildingHouseingTools_Order_Default", "Building Houseing Tools"),
            ("IronPotsAndPans_Order_Default", "Iron Pots And Pans"),
            ("WoodworkingTools_Order_Default", "Woodworking Tools"),
            ("Cabbage_Order_Default", "Cabbage"),
            ("MountainPotato_Order_Default", "Mountain Potato"),
            ("Mushrooms_Order_Default", "Mushrooms"),
            ("CopperCoins_Order_Default_0", "Copper Coins_0"),
            ("TinCoins_Order_Default", "Tin Coins"),
        ],
    ),
]
